# Generated by Django 4.2.16 on 2024-12-21 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='auction_listing',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='higest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auctionlistings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
