# Generated by Django 4.2.16 on 2025-01-01 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlistings_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='higest_bidder',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
